// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntOcXQuyBq5UQaK_aAg4eJ8F2ermymM8',
    appId: '1:233453515314:android:92884626e9dfc0aec6822b',
    messagingSenderId: '233453515314',
    projectId: 'project-6664351583735870109',
    databaseURL: 'https://project-6664351583735870109-default-rtdb.firebaseio.com',
    storageBucket: 'project-6664351583735870109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCgyRjn_kx0EnSRkUf4rWXqHAR9uHT3t4',
    appId: '1:233453515314:ios:2154c313701fa1f2c6822b',
    messagingSenderId: '233453515314',
    projectId: 'project-6664351583735870109',
    databaseURL: 'https://project-6664351583735870109-default-rtdb.firebaseio.com',
    storageBucket: 'project-6664351583735870109.appspot.com',
    androidClientId: '233453515314-0uks2f9372f1lk9da078cad6je6in2db.apps.googleusercontent.com',
    iosClientId: '233453515314-46d2pnvp5tm7d2q5rqq31hq7cgfjt020.apps.googleusercontent.com',
    iosBundleId: 'com.example.fb11305202',
  );
}
